### ISSUE TITLE
The top tier should be limited to 11.0

### ISSUE THREAD

**Issue by Lutra-Fs** [ControlNet/wt-data-project.visualization#2]
No 12.0 now…

**Comment by ControlNet** [comment]
Actually, this is how the top-tier matching works. You can try to play 11.0 vehicles in ground RB, and you will see the spawn points are varied.

**Comment by Lutra-Fs** [comment]
Thanks for clarifying. I understand that. But should we limit the displayed BR to 11.0? As the actual highest BR is 11.0.

**Comment by ControlNet** [comment]
Yes, it's possible, I will implement that soon on the web visualization.
